### ISSUE TITLE
Is this library abandoned?

### ISSUE THREAD

**Issue by martflu** [LitGroup/money.dart#26]
We currently use the version published to pub and are wondering if you still plan to maintain it. The reason I ask is that we are switching to dart 2.0 the moment and your library has a restriction in `pubspec.yaml` to  sdk: ">=1.19.0 <2.0.0".

**Comment by Sharom** [comment]
Hello, @martflu.

I am a bit busy now but I will try to find some time to make this library compatible with Dart 2.0.

**Comment by Sharom** [comment]
Hello, @martflu. I have released `0.2.0`. Library has been migrated to Dart 2.x.
There are no changes of API.
