### ISSUE TITLE
Version solving failed

### ISSUE THREAD

**Issue by creatint** [LitGroup/money.dart#29]
When I use the latest money, there's something wrong.

> Running "flutter packages upgrade" in mm...
The current Dart SDK version is 2.0.0-dev.58.0.flutter-f981f09760.
Because mm depends on money >=0.2.0 which requires SDK version >=2.0.0 <3.0.0, version solving failed.
pub upgrade failed (1)

**Comment by Sharom** [comment]
Hello, @creatint.

Is it absolutely required for you to use this release of Flutter? Or can you use a fresh release of Flutter with the last version of Dart SDK?

**Comment by Sharom** [comment]
@creatint ??
