### ISSUE TITLE
Export the list of currencies

### ISSUE THREAD

**Issue by haarts** [LitGroup/money.dart#31]
I want to use this library to construct a `DropdownButton` in Flutter. For this I need to have a list of currencies. This library has that list but doesn't expose it. I think it would be a good idea to do so. 
Perhaps as something as trivial as this:

```dart
Iterable<Currency> currencies =_currencies.values;
```

**Comment by Sharom** [comment]
Hello @haarts.
This library was made for calculationof money. If you need a list of currencies in your view -- make own view model. You can translate currency from the view model to the logic model by code (as an example).

Do not mess logic model and view model, read about tiered architecture or architecture of ports and adapters (also named hexagonal architecture).
