### ISSUE TITLE
There's no way to convert between Money and MoneyData

### ISSUE THREAD

**Issue by oysterpack** [LitGroup/money.dart#36]
There's no way to convert between Money and MoneyData.

**Comment by Sharom** [comment]
@oysterpack See https://github.com/LitGroup/money.dart/blob/a70e339c7b4bb3aa695eb5ad69bbbf0c2936e803/lib/src/money.dart#L60

You can implement encoding to any representation with this API.

**Comment by oysterpack** [comment]
MoneyMoney does not expose BigInt subunits, Currency currency properties. Thus, we are not able to convert Money into MoneyData.

For example.

```
final usd = Currency.withCodeAndPrecision('USD', 2);
var balance = Money.withSubunits(BigInt.from(500), usd);
balance *= 0.03;
// How can I convert from Money to MoneyData? 
MoneyData moneyData =  // MoneyData.from(balance);
```

**Comment by Sharom** [comment]
Subunits will not be exposed as a property of Money. It's internal data representation.

To convert Money to your DTO or String or any other representation use encoding/decoding API of the `Money` type.

`MoneyData` is a DTO using in the formatting API.

**Example**

```dart
import 'package:money/money.dart';

/// Encodes money value to string with currency code and subunits.
class MyStringFormatter implements MoneyEncoder<String> {

    String encode(MoneyData data) {
        return '${data.currency.code} ${data.subunits}';
    }
}

void main() {
    final usd = Currency.withCodeAndPrecision('USD', 2);
    final price = Money.withSubunits(BigInt.from(500), usd);

    print(price.encodedBy(MyStringEncoder())); // => 'USD 500'
}
```

**Comment by Sharom** [comment]
@oysterpack I am closing the issue. Let me know if you still need a help.
