### ISSUE TITLE
Custom formatting or abi

### ISSUE THREAD

**Issue by bsutton** [LitGroup/money.dart#37]
Thanks for the work on this class.

One short coming is that there is no way to do custom formatting of money values.

I either need the ability to obtain the integer and fractional parts separately so that I can then create a custom format or the library needs the ability to provide at least a set of common formats.

e.g.
$10.00 USD
10.00 USD
$10.00
$10 USD
$10
10
There a also cases where you want to create abbreviations. For instance in stock market apps we presented large numbers to 6 digits max.

e.g.
10K
1.2M

I will push a commit which at least allows a user to get the integer and factional parts.

**Comment by Sharom** [comment]
Hello, @bsutton.

There is the API for encoding/decoding any representation of Money.
Check methods `Money.decoding()` and `Money.encoded()` and the interfaces `MoneyEncoder` & `MoneyDecoder`.

You can also see the tests as a simplified example: https://github.com/LitGroup/money.dart/blob/master/test/money_coding_test.dart

**Comment by bsutton** [comment]
I think that this needs some more documentation as even after reading the
test units it not at all clear what the intent of the encoders are.

I've got some doc changes I will push tomorrow that I think make the usage
of the main classes more approachable. I will have a closer look at the
encoders as well.

**Comment by bsutton** [comment]
I've just pushed documentation changes and added a new method Money.format(String pattern).

Hopefully you like it :)
